### ISSUE TITLE
ICYStream not working correctly after buffer underrun?

### ISSUE THREAD

**Issue by h3ndrik** [earlephilhower/ESP8266Audio#124]
I experience the following problem:
After an underrun happenes the AudioGeneratorMP3 loses synchronization, seems to sync for a few frames and then loses sync again. I first worked through all of the MP3 code but finally swapped ICY... for HTTPStream and finally it can re-gain sync.

I believe there is an error somewhere in the code calculating the icy blocks where something gets mis-aligned. This happenes to me after the buffer complains about an underrun. (I didn't see any message that it does a reconnect, if that matters.) And the output of the callbacks (title, ...) are garbled afterwards.

I'm not sure this is the cause. (The pipeline in my example is long: AudioFileSourceICYStream -> AudioFileSourceBuffer -> AudioGeneratorMP3 -> AudioOutputI2S)
But that would would be a resonable cause as this would delete bytes of the mp3 data every few kB.

**Comment by itsjustvenky** [comment]
Even I am getting buffer underrun and decording errors while playing a small mp3 file (44khz, 32 bit per sample). The mp3 file is pulled from internet website.
Ex : http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02-128k.mp3

**Comment by rv9c** [comment]
I also ran into this problem. Used esp-wroom-32 and the latest version of arduino-esp32.

 Noticed this: Using a bunch (AudioFileSourceICYStream -> AudioFileSourceBuffer -> AudioGeneratorMP3 -> AudioOutputI2S) on the Internet stations transmitting metadata goes hiccups that. At Internet stations that do not transmit metadata, there is no problem

If I start using this bundle (AudioFileSourceHTTPStream -> AudioFileSourceBuffer -> AudioGeneratorMP3 -> AudioOutputI2S), then all stations are reproduced without hiccups and breaks, but there is no metadata accept function.

I concluded that the problem is in the AudioFileSourceICYStream module, in particular, obtaining metadata from the broadcasting station.

I think that the AudioFileSourceICYStream does not correctly select metadata from the stream.

Sorry for my English)
