### ISSUE TITLE
Synthesizer

### ISSUE THREAD

**Issue by ChrisMicro** [earlephilhower/ESP8266Audio#130]
Is there a simple way to use your library and attach a synthesizer to it?
Here I did it by directly using I2S:
https://github.com/ChrisMicro/EquationComposer/blob/master/examples/_020_ESP8266_withPoti/_020_ESP8266_withPoti.ino
But it would be convenient to use your library because it is easy to switch between I2S,DAC and sigma delta.
Probably you could add a 'basic' example producing a sine wave to your examples list.

**Comment by earlephilhower** [comment]
It's pretty simple.  Just instantiate a out = new AudioOutput(I2S,I2SNODAC,etc.) and set it up (out->SetRate(), etc.).  Then instead of calling i2s_write_sample(), call out->ConsumeSample().  You will need to check the return code, as it doesn't block, but on failure you can just retry until there is buffer space.
