### ISSUE TITLE
PlayMIDIFromSPIFFS distortion

### ISSUE THREAD

**Issue by pety01** [earlephilhower/ESP8266Audio#134]
Thank you for the great library! I have been playing with this library for weeks and trying to get some valuable sound (music) using the PlayMIDIFromSPIFFS skeleton. Actually as I start to use the basic example it doesn't play the Fur Elise. The sound has a distortion, faltering and crackling. I am using NodeMCU 1.0/1.4 Prebuilt/160MHz without DAC.  I have tried the WAV and MP3 skeleton codes, they are fine. What could be the problem?The MIDI should be one "tracked"? Using DAC would solve (I doubt)? Anybody had similar issue playing MIDI? Could be possible the MIDI + SF are not in synch or kind of kill each other? I have no more ideas to fix it. Many thanks for sharing experiences or ideas.

**Comment by earlephilhower** [comment]
The problem is that SPIFFS is very slow to begin with, and can sometimes be exceedingly slow even on the same hardware.  The crackling is buffer underrun because SPIFFS can't read out the samples fast enough.  I started work on a replacement filesystem which was 2-4x faster, (see ESP8266FastROMFS) which works well enough to run the MIDI sample, but I didn't get time to actually finish the testing so it's not been included.  You could try using a SD card, that could very well be faster than SPIFFs.
