### ISSUE TITLE
AudioGeneratorMP3: "synth"=malloc(sizeof(struct mad_synth))  returns NULL randomly.

### ISSUE THREAD

**Issue by ninghuiy** [earlephilhower/ESP8266Audio#196]
My program keeps playing online MP3 files in a loop, sometimes the mp3->begin() just failed.  I found out that "synth" does not really allocate memory sometimes and retruns NULL.  I am wondering the issue is calling malloc() and free() too many (not sure). 

Also I noticed the "preallocateSpace" is an another way to do that. should I use that? I am new to C programming and ESP8266, and I have no idea how to solve this. 

Thanks

```
void Player::loop()
{
  Serial.printf_P(PSTR("running: %d\n"),Mp3->isRunning());
  if (Mp3->isRunning()) {
    if (Mp3->loop()) {
      Mp3->stop();
      stopI2s();

      Serial.printf_P(PSTR("MP3 done. Free Heap: %dkB\n"), ESP.getFreeHeap() / 1024);
      analogWrite(LED_PIN, LED_IDLE_LEVEL);
    }
  } else {
    if (!_playQueue.isEmpty()) {
      playNext();
    }
  }
}
```

**Comment by earlephilhower** [comment]
Yes, this is a memory issue.  The preallocation would help ensure available space and if you're doing lots of playback operations I'd definitely use it.

The problem is basically one of memory fragmentation.  Since the ESP8266 has no MMU, a single byte's usage in the wrong spot could make it impossible to file the needed 28K or so, even if the free heap was 40KB in size.
