### ISSUE TITLE
Streaming via plain TCP instead of ICY or HTTP?

### ISSUE THREAD

**Issue by mihuljinac** [earlephilhower/ESP8266Audio#332]
Would it be possible to modify existing source (AudioFileSourceHTTPStream) to support audio streaming via plain TCP instead of http/icy?
Use-case would be using tcp client on Android with push-to-talk button to transmit audio from microphone to ESP32 tcp server.
TCP server on ESP32 would accept incoming connection and play audio that is received via plain socket connection.
TCP server would be always listening for incoming connection so whenever client connects there is audio on the output.
For Android app I'm using https://github.com/charlesmcchan/MediaStreamer/tree/master/src/tw/rascov/MediaStreamer as a template, only modified to transmit audio via tcp client instead of server.
Main reason for posting this here is to see if it already exists, otherwise I will share my experience.

**Comment by earlephilhower** [comment]
Something like that would definitely be possible, but I'd just start from scratch.  Sounds like you are just sending raw samples over a plain TCP port, so for that you'd need to write a very simple AudioFileSourceTCP.  You would also need to write a pass-through AudioGeneratorRaw() which would just read the source and write bytes to the AudioOutput* .  Only thing is you'd probably need to specify the bits-per-sample, channels, and frequency in the AudioFileSourceTCP constructor since with raw bytes you don't know what format you're getting.

Good luck!
