### ISSUE TITLE
Minimal hardware?

### ISSUE THREAD

**Issue by prandeamus** [earlephilhower/ESP8266Audio#413]
Question/Guidance needed

Is it possible to run ESP8266Audio on the smaller 8266 boards - I'm thinking specifically of ESP-01 boards, very few exposed pins, like the ones shown here https://diyprojects.io/esp01-get-started-arduino-platformio-ide-module-choose-pinout/#.YPWlY-hKhPY 

Let's say we have only GPIO0 and GPIO2, RX and TX exposed and a very simple requirement where I press a button and an mp3 sound is played, a digital doorbell, say. Could the software psuedo-DAC be run from the RX pin and a button attached to GPIO 0 or 2? 

Obviously there will be more limitations if you have only 512K ram vs 1M ram, and with a very small number of pins available there will be other restrictions, but it is possible?

I have a NodeMCU board and have a play, but wondered if there was any guidance available?

**Comment by earlephilhower** [comment]
Yes, that would work.  You would only be able to use the `I2SNoDAC` path since the full I2S interface is not pinned out, but as long as you can fit the code in flash I think it would work.  As for the GPIO usage, there could be some issue w/GPIO0 IIRC as it is used on chip startup to determine boot mode.

It's exactly the same ESP8266 chip on the ESP-01 as other boards, just fewer pins and tinier flash.

Good luck!
