### ISSUE TITLE
ESP32 AudioI2S causes relay switch to 'buzz'

### ISSUE THREAD

**Issue by renegadeandy** [earlephilhower/ESP8266Audio#63]
Hi!

I have an ESP32 board, the oooouuuu development board. I have the following sketch, where relayPin1 is attached to a relay board(https://www.amazon.co.uk/gp/product/B06XKQQXKW/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)

When I run the sketch, the sampleaac.h audio plays, but as soon as it has finished, the relay which is powered (sending low to relayPin1) makes a buzzing noise. Removing the ESP8266Audio library from the sketch stops the buzz. Note that before, and during the audio playing, there is no 'feedback buzz' from the relay, it only starts after the audio is complete. Help!

The code for the project which recreates the issue can be found at this git repo:
https://bitbucket.org/renegadeandy/audio_bug_buzz

Grab it with:

`git clone https://bitbucket.org/renegadeandy/audio_bug_buzz`

**Comment by earlephilhower** [comment]
Sounds like you have a crosstalk issue. Try doing an AudioOutputI2S->stop() to disable the interface and clocks.

**Comment by renegadeandy** [comment]
Aha - that solves it, thank you. I assume the Audio from SPIFFS now works on ESP32 since they fixed the SPIFFS support?

**Comment by earlephilhower** [comment]
I've not done any ESP32 work recently, but others say it does work if you apply a pull request that's been floundering for a while now or get an older SPIFFs toolset/GIT tag.  Check the issues here for the link, or the README.md.  Unfortunately it seems like the ESP32-Arduino is a little less responsive than the ESP8266-Arduino team (I think the IDK is really pushed for the ESP32 so that probably explains it).

**Comment by renegadeandy** [comment]
What is the IDK?

**Comment by earlephilhower** [comment]
Meant to say IDF.  Their build platform.  Was thinking last word as "Kit" not "Foundation"
