### ISSUE TITLE
ESP8266Audio compilation error in V3.0.0-Release of Arduino-esp32

### ISSUE THREAD

**Issue by Zhentao-Lin** [earlephilhower/ESP8266Audio#683]
This is a very practical and easy to use library, I really enjoy using it to do some audio development.
Today, after updating my Arduino-esp32 to version 3.0.0-Release, I found that the compilation failed. As my personal ability level is limited, I ask for your help. Here is my error message.

![1](https://github.com/earlephilhower/ESP8266Audio/assets/62634190/d0c702aa-4d9d-48b7-addc-2c2edb10b339)

Thank you again.

**Comment by earlephilhower** [comment]
Espressif seems to have broken existing code with the (IMHO reasonable and a good idea in the long term!) change from `WiFiClient` to `NetworkClient` in 3.0.0.  Since they have an entire Ethernet MAC onboard in addition to the WiFi radio, it makes sense.  On the Pico we ended up keeping `WiFiClient` and just letting it work on anything, wired or wireless.

All network code for the ESP32 will need to be rewritten to use the new class names.  I'm not really an ESP32 user so hopefully someone here will have the time and knowledge to to the transition and throw a PR out...

**Comment by Lebo77** [comment]
If I don't use the WiFi functions in this library (all the audio I am playing is local) is there a workaround to comment out all the network stuff?
